---
sudo: required
services:
  - docker

before_install:
  - docker build -t ejosafat/fib-test -f ./client/Dockerfile.dev ./client
  
script:
  - docker run ejosafat/fib-test npm test -- --coverage

after_success:
  - docker build -t ejosafat/docker-course-fib-multi-client ./client
  - docker build -t ejosafat/docker-course-fib-multi-nginx ./nginx
  - docker build -t ejosafat/docker-course-fib-multi-server ./server
  - docker build -t ejosafat/docker-course-fib-multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to the docker hub
  - docker push ejosafat/docker-course-fib-multi-client
  - docker push ejosafat/docker-course-fib-multi-nginx
  - docker push ejosafat/docker-course-fib-multi-server
  - docker push ejosafat/docker-course-fib-multi-worker

