---
version: '2'
services:
  postgres:
    image: 'postgres:latest'
  redis:
    image: 'redis:latest'
  nginx:
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - '3050:80'
  api:
    build:
      dockerfile: Dockerfile.dev
      context: ./server
    volumes:
      - /app/node_modules # Marker to leave this folder untouched, no sync with host folder
      - ./server:/app
    environment:
      - REDIS_HOST=docker-course-redis
      - REDIS_PORT=6379
      - PGUSER=postgres
      - PGHOST=postgres
      - PGDATABASE=fib_values
      - PGPASSWORD=postgres_password
      - PGPORT=5432
  client:
    build:
      dockerfile: Dockerfile.dev
      context: ./client
    volumes:
      - /app/node_modules # Marker to leave this folder untouched, no sync with host folder
      - ./client:/app
  worker:
    environment:
      - REDIS_HOST=docker-course-redis
      - REDIS_PORT=6379
    build:
      dockerfile: Dockerfile.dev
      context: ./worker
    volumes:
      - /app/node_modules # Marker to leave this folder untouched, no sync with host folder
      - ./worker:/app
    